### ISSUE TITLE
Failed postinstall script on debian based distros

### ISSUE THREAD

**Issue by keksas** [nwjs/npm-installer#21]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
npm install nw -g
> nw@0.12.1 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
```

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.

**Comment by shama** [comment]
Sorry but Debian is in the wrong here. Scripts can't just simply change to use "nodejs".

`node` is the name of the binary that gets installed everywhere else. This is because everywhere in the node ecosystem relies on the binary being named `node`.

In addition to other systems relying on `node`, other installers installing `node`, `node` used internally by Node.js... here are [78,631 instances](https://github.com/search?utf8=%E2%9C%93&q=%22%23%21%2Fusr%2Fbin%2Fenv+node%22&type=Code&ref=searchresults) of users using `#!/usr/bin/env node`.

Whoever decided to rename `node` to `nodejs` was very ill informed about the Node.js ecosystem.

You'll need to either symlink `node` to `nodejs` or re-install node which will properly restore the `node` binary. Sorry.
