### ISSUE TITLE
Ubuntu 15.04 install problems

### ISSUE THREAD

**Issue by lucevers** [nwjs/npm-installer#24]
Info

 sudo npm install nw -g
[sudo] password for master: 
/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw

> nw@0.12.2 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! nw@0.12.2 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.12.2 postinstall script.
npm ERR! This is most likely a problem with the nw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nw
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-21-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nw" "-g"
npm ERR! cwd /home/master/NW
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/master/NW/npm-debug.log
npm ERR! not ok code 0

**Comment by shama** [comment]
Please see this comment: https://github.com/nwjs/npm-installer/issues/21#issuecomment-94517559

Due to a conflict, Debian renamed the `node` binary to `nodejs` which of course breaks everything. They really should just not package node.js with their dist. You'll need to properly install node.js to get the correct `node` binary.
