### ISSUE TITLE
nw bin script has CRLF endings

### ISSUE THREAD

**Issue by Kagami** [nwjs/npm-installer#37]
nw bin script has CRLF endings after installing nw from npm, thus making it impossible to run it without conversion on Linux:

```
$ npm i nw@0.13.0-beta5sdk
$ file -L node_modules/.bin/nw
node_modules/.bin/nw: Node.js script, ASCII text executable, with CRLF line terminators
$ node_modules/.bin/nw 
: No such file or directory
$ dos2unix -F node_modules/.bin/nw
dos2unix: converting file node_modules/.bin/nw to Unix format...
$ node_modules/.bin/nw
[0207/192912:INFO:nw_package.cc(175)] ...runs ok
```

Could you please use LF endings for this file?

**Comment by Mithgol** [comment]
That's right. It was caused by Git's `core.autocrlf` set to `true` in my settings:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/13005180/30faf274-d191-11e5-9ea3-38532469ecd5.png)

I've converted line endings in `bin/nw` back to LF and republished without CR as `nw@0.13.0-beta5sdk-1`.

[TIL](http://www.urbandictionary.com/define.php?term=TIL "today I learned") that `npm publish` should also have something like Git's `core.autocrlf` setting (issue npm/npm#2097), but it hasn't.

Naturally, all of my previous publishes from Windows have this problem. I am sorry, but I probably won't be able to fix them because `npm publish --force` is [forbidden](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f) nowadays.

**Comment by Kagami** [comment]
>I've converted line endings in bin/nw back to LF and republished without CR as nw@0.13.0-beta5sdk-1

Now it works, thanks!
